name: GitHub 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11.4]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "Running experiment file for unit test."
      - name: List files in the repository
        run: |
          ls -r ${{ github.workspace }}
      - name: Install dep
        run:  pip3 install --no-cache-dir -r requirements.txt
      - name: Run experiment
        run:
          experiment.py